# Plotting the Data

In [23]:
import pandas as pd
import altair as alt

In [24]:
df = pd.read_csv('./fdi_remit_oda.csv')

In [25]:
df

    year     fdi_total  remittances_total     oda_total
0   1990  2.031026e+10       2.727300e+10  4.566382e+10
1   1991  2.749659e+10       2.840200e+10  4.797208e+10
2   1992  4.158727e+10       3.339100e+10  4.517123e+10
3   1993  6.067204e+10       3.505400e+10  4.080313e+10
4   1994  7.984242e+10       3.952800e+10  4.554756e+10
5   1995  8.928139e+10       4.565500e+10  4.441897e+10
6   1996  1.108002e+11       4.989500e+10  4.008437e+10
7   1997  1.434077e+11       5.983500e+10  3.541869e+10
8   1998  1.418889e+11       5.812400e+10  3.738680e+10
9   1999  1.529906e+11       6.398700e+10  3.871808e+10
10  2000  1.405397e+11       7.048900e+10  3.568206e+10
11  2001  1.563496e+11       7.969000e+10  3.932458e+10
12  2002  1.482108e+11       9.455700e+10  4.473242e+10
13  2003  1.567975e+11       1.179340e+11  5.234248e+10
14  2004  2.085291e+11       1.352760e+11  5.754961e+10
15  2005  2.903897e+11       1.914990e+11  8.536165e+10
16  2006  3.786612e+11       2.245810e+11  8.101066e+10
17  2007  5.303854e+11       2.733250e+11  7.885090e+10
18  2008  6.104320e+11       3.196670e+11  8.719081e+10
19  2009  4.246672e+11       3.035330e+11  8.689201e+10
20  2010  6.210164e+11       3.397170e+11  8.806494e+10
21  2011  7.257458e+11       3.824850e+11  9.468993e+10
22  2012  6.739950e+11       4.047300e+11  9.339273e+10
23  2013  7.422103e+11       4.228440e+11  1.040365e+11
24  2014  6.408593e+11       4.442950e+11  1.020849e+11
25  2015  6.077214e+11       4.465450e+11  9.712769e+10
26  2016  5.511690e+11       4.404760e+11  1.035335e+11
27  2017  5.456278e+11       4.770160e+11  1.092736e+11
28  2018  6.062787e+11       5.235880e+11  1.112706e+11
29  2019  5.657494e+11       5.462270e+11  1.075248e+11
30  2020  5.364865e+11       5.419450e+11  1.356689e+11
31  2021  7.529980e+11       5.969850e+11  0.000000e+00

In [26]:
df = df.drop(columns=['fdi_total'])

In [27]:
df['remittances_total'] = df['remittances_total']/1000000000

df['oda_total'] = df['oda_total']/1000000000

In [28]:
df

    year  remittances_total   oda_total
0   1990             27.273   45.663820
1   1991             28.402   47.972080
2   1992             33.391   45.171230
3   1993             35.054   40.803130
4   1994             39.528   45.547560
5   1995             45.655   44.418970
6   1996             49.895   40.084370
7   1997             59.835   35.418690
8   1998             58.124   37.386800
9   1999             63.987   38.718080
10  2000             70.489   35.682060
11  2001             79.690   39.324580
12  2002             94.557   44.732420
13  2003            117.934   52.342480
14  2004            135.276   57.549610
15  2005            191.499   85.361650
16  2006            224.581   81.010660
17  2007            273.325   78.850900
18  2008            319.667   87.190810
19  2009            303.533   86.892010
20  2010            339.717   88.064940
21  2011            382.485   94.689930
22  2012            404.730   93.392730
23  2013            422.844  104.036490
24  2014            444.295  102.084910
25  2015            446.545   97.127690
26  2016            440.476  103.533501
27  2017            477.016  109.273580
28  2018            523.588  111.270590
29  2019            546.227  107.524789
30  2020            541.945  135.668891
31  2021            596.985    0.000000

In [29]:
# remove the data for 2021 - because we don't have the ODA for that year 

df = df[df['year'] != 2021]

In [32]:
df['year'] = pd.to_datetime(df['year'], format='%Y')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_15989/3509222785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = pd.to_datetime(df['year'], format='%Y')

In [33]:
# use altair to create a chart with both remittances and ODA on the y axis 

base = alt.Chart(df.reset_index()).encode(x='year')

alt.layer(
    base.mark_line(color='blue').encode(y='oda_total'),
    base.mark_line(color='red').encode(y='remittances_total')
).properties(
    width=600,
    height=400
)

/Users/kellywaldron/.pyenv/versions/3.11.0rc2/lib/python3.11/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():

alt.LayerChart(...)